-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK
JOIN BOOK_SALES USING (BOOK_ID)
JOIN AUTHOR USING (AUTHOR_ID)
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
 





-- TOTAL_SALES = 판매량 * 판매가