-- 코드를 작성해주세요
WITH A AS (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) AS COLONYRATE
    FROM ECOLI_DATA 
)

SELECT ID, 
    CASE
        WHEN COLONYRATE = 4 THEN 'CRITICAL'
        WHEN COLONYRATE = 3 THEN 'HIGH'
        WHEN COLONYRATE = 2 THEN 'MEDIUM'
        WHEN COLONYRATE = 1 THEN 'LOW'
    END AS COLONY_NAME
FROM A
ORDER BY ID