-- 코드를 작성해주세요
-- 모든 아이디 / 년도 중 가장 큰 개체 값 - 해당 아이디의 개체 값
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA A 
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) B
ON YEAR(A.DIFFERENTIATION_DATE) = YEAR
ORDER BY YEAR, YEAR_DEV