-- 코드를 입력하세요
-- SELECT * FROM FIRST_HALF ORDER BY TOTAL_ORDER DESC
SELECT A.FLAVOR 
FROM FIRST_HALF A, ICECREAM_INFO B
WHERE A.TOTAL_ORDER > 3000
AND B.INGREDIENT_TYPE = "fruit_based"
AND A.FLAVOR = B.FLAVOR
ORDER BY TOTAL_ORDER DESC