-- 코드를 작성해주세요
WITH SORTED_TABLE AS (
    SELECT ID, FISH_NAME, LENGTH, 
        ROW_NUMBER() OVER(PARTITION BY FISH_NAME ORDER BY LENGTH DESC) AS SEQUENCE
    FROM FISH_INFO A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
)

SELECT ID, FISH_NAME, LENGTH
FROM SORTED_TABLE
WHERE SEQUENCE = 1
ORDER BY ID