-- 코드를 작성해주세요 점수, 사번, 성명, 직책, 이메일
WITH POTG AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
)

SELECT SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES A JOIN POTG B
ON A.EMP_NO = B.EMP_NO